import type { Language } from "@uiverse/schema";
import { useUiverseStore } from "@/lib/store";

const copy = {
  ko: {
    common: {
      appName: "Uiverse",
      projects: "프로젝트",
      settings: "설정",
      help: "도움말",
      helpCenter: "도움말 센터",
      feedback: "의견 보내기",
      createProject: "새 프로젝트",
      export: "내보내기",
      openEditor: "편집 열기",
      returnToDashboard: "대시보드로 돌아가기",
      live: "실시간",
      language: "언어",
      korean: "한국어",
      english: "English",
      screen: "화면",
      screens: "화면",
      project: "프로젝트",
      close: "닫기",
      savedLocally: "로컬에 저장됩니다"
    },
    topHeader: {
      badge: "직관적인 시각 편집기",
      quickLink: "작업 흐름"
    },
    workspaceNav: {
      eyebrow: "워크스페이스",
      title: "Uiverse 스튜디오",
      description: "프로젝트, 설정, 도움말을 한 곳에서 관리하세요.",
      elements: "핵심 기능",
      elementLine1: "드래그 없이도 눌러서 요소 추가",
      elementLine2: "코드 없이 색상과 배치 수정",
      elementLine3: "React / HTML 코드 내보내기"
    },
    dashboard: {
      badge: "로컬 UI 설계 도구",
      title: "코드 작성 전에 화면 구조부터 쉽게 만들어보세요.",
      description: "프로젝트를 만들고, 화면을 고르고, 요소를 추가한 뒤, 색상과 배치와 간격을 조정하고, 마지막에 코드를 내보낼 수 있게 구성했습니다.",
      searchPlaceholder: "프로젝트 이름이나 설명 검색",
      quickStartTitle: "처음이라면 여기부터 시작하세요",
      quickStartSteps: [
        "새 프로젝트를 만듭니다.",
        "왼쪽에서 화면을 고릅니다.",
        "요소를 추가하고 오른쪽에서 색상과 문구를 바꿉니다."
      ],
      quickStartHelp: "자세한 도움말 보기",
      quickStartCreate: "바로 새 프로젝트 만들기",
      dashboardTitle: "프로젝트 대시보드",
      dashboardDescription: "프로젝트마다 여러 화면을 가질 수 있고, 화면별로 편집 후 코드를 따로 내보낼 수 있습니다.",
      recentTitle: "최근 작업",
      recentDescription: "최근에 수정한 프로젝트를 빠르게 다시 엽니다.",
      metrics: {
        projects: "프로젝트 수",
        screens: "화면 수",
        components: "요소 수"
      },
      cardScreens: "개 화면",
      cardNodes: "개 요소"
    },
    settings: {
      eyebrow: "설정",
      title: "언어, 색상, 기본 내보내기 형식을 쉽게 바꾸세요.",
      description: "복잡한 개발자 설정 대신 핵심 항목을 먼저 보여줍니다.",
      profileTitle: "기본 환경",
      profileDescription: "`uiverse.settings.v1`에 로컬 저장됩니다.",
      profileName: "이름",
      email: "이메일",
      exportTarget: "기본 내보내기 형식",
      accentColor: "포인트 색상",
      accentHelp: "색상칩을 누르거나 팔레트에서 고르세요. 직접 코드 입력은 선택입니다.",
      language: "표시 언어",
      storageTitle: "저장 구조",
      storageDescription: "현재 앱이 로컬에 저장하는 데이터입니다.",
      inspectJson: "JSON 보기",
      storageProjects: "프로젝트, 화면, 요소 구조, 마지막으로 연 화면을 저장합니다.",
      storageSettings: "언어, 포인트 색상, 기본 내보내기 형식을 저장합니다.",
      summaryTitle: "현재 시스템 요약",
      themeMode: "테마",
      darkOnly: "다크 모드 V1",
      exportFormats: "내보내기 형식",
      dataModel: "구조",
      summaryModel: "사용자 -> 프로젝트 -> 화면 -> 요소"
    },
    editor: {
      project: "프로젝트",
      screens: "화면 목록",
      elementPalette: "요소 추가",
      clickToInsert: "눌러서 추가",
      nodeTree: "레이어 트리",
      dragOnCanvas: "캔버스에서 위치 이동",
      dragInLayers: "레이어 패널에서 순서 변경",
      visualEditor: "시각 편집기",
      arrangement: "배치 구성",
      arrangementHint: "세로, 가로, 2열, 3열 같은 구성을 바로 적용할 수 있습니다.",
      exportView: "코드 보기",
      canvasTab: "화면",
      codeTab: "코드",
      livePreview: "실시간 React/Tailwind 미리보기",
      livePreviewHint: "현재 화면 기준으로 생성된 코드입니다.",
      inspector: "속성 편집",
      layerTab: "레이어",
      contentTab: "내용",
      styleTab: "스타일",
      layerSearchPlaceholder: "레이어 이름 검색",
      layerHint: "레이어를 끌어서 순서를 바꾸고, 컨테이너 위에 놓으면 안쪽으로 넣을 수 있습니다.",
      styleHint: "위쪽 빠른 카드에서 바로 바꾸고, 더 자세한 값만 아래 세부 수치에서 펼쳐 수정합니다.",
      addInside: "안에 추가",
      deleteLayer: "레이어 삭제",
      moveUp: "위로",
      moveDown: "아래로",
      cannotDeleteRoot: "루트 화면은 지울 수 없습니다.",
      addStack: "스택 추가",
      content: "내용",
      layerName: "레이어 이름",
      textValue: "문구",
      buttonLabel: "버튼 문구",
      placeholder: "안내 문구",
      imageSrc: "이미지 주소",
      altText: "대체 텍스트",
      inherit: "상위값 사용",
      breakpointLabel: "현재 기준",
      previewWidth: "미리보기 폭",
      noSelection: "캔버스나 레이어에서 요소를 하나 선택해 주세요.",
      noLayerSelection: "선택된 레이어가 없습니다.",
      projectNotFound: "프로젝트를 찾을 수 없습니다",
      projectNotFoundBody: "선택한 프로젝트 또는 화면이 로컬 저장소에 없습니다.",
      deviceDesktop: "데스크톱",
      deviceTablet: "태블릿",
      deviceMobile: "모바일",
      groups: {
        typography: "글자",
        layout: "배치",
        background: "배경",
        border: "테두리",
        effects: "효과"
      },
      properties: {
        position: "배치 기준",
        top: "위쪽 좌표",
        left: "왼쪽 좌표",
        right: "오른쪽 좌표",
        bottom: "아래쪽 좌표",
        zIndex: "앞뒤 순서",
        fontSize: "글자 크기",
        fontWeight: "글자 두께",
        lineHeight: "줄 간격",
        letterSpacing: "글자 간격",
        textAlign: "정렬",
        color: "글자 색상",
        display: "표시 방식",
        direction: "정렬 방향",
        gap: "간격",
        align: "세로 맞춤",
        justify: "가로 맞춤",
        gridColumns: "칸 수",
        width: "너비",
        height: "높이",
        padding: "안쪽 여백",
        margin: "바깥 여백",
        backgroundColor: "배경 색상",
        backgroundGradient: "배경 그라디언트",
        borderStyle: "테두리 모양",
        borderWidth: "테두리 두께",
        borderColor: "테두리 색상",
        borderRadius: "모서리 둥글기",
        borderTopLeftRadius: "왼쪽 위 모서리",
        borderTopRightRadius: "오른쪽 위 모서리",
        borderBottomRightRadius: "오른쪽 아래 모서리",
        borderBottomLeftRadius: "왼쪽 아래 모서리",
        opacity: "투명도",
        boxShadow: "그림자"
      },
      options: {
        position: { static: "흐름 배치", relative: "기준 박스", absolute: "자유 배치" },
        display: { block: "블록", flex: "가로/세로 배치", grid: "격자", none: "숨김" },
        direction: { row: "가로", column: "세로" },
        align: { start: "위/왼쪽", center: "가운데", end: "아래/오른쪽", stretch: "늘리기" },
        justify: { start: "시작", center: "가운데", end: "끝", between: "양끝 정렬", around: "주변 간격" },
        gridColumns: { "1": "1칸", "2": "2칸", "3": "3칸", "4": "4칸" },
        borderStyle: { solid: "실선", dashed: "점선", none: "없음" },
        textAlign: { left: "왼쪽", center: "가운데", right: "오른쪽" }
      },
      presets: {
        stack: "세로 쌓기",
        row: "가로 줄 배치",
        twoColumn: "2열 배치",
        threeColumn: "3열 배치",
        cardGrid: "카드형 그리드",
        compactGap: "좁게",
        normalGap: "보통",
        roomyGap: "넓게",
        tightPadding: "좁은 여백",
        normalPadding: "보통 여백",
        widePadding: "넓은 여백"
      }
    },
    exportView: {
      title: "코드 내보내기",
      description: "공통 globals 파일과 화면별 파일을 함께 확인하고 필요한 파일만 내려받을 수 있습니다.",
      target: "내보내기 형식",
      screenFilter: "화면 선택",
      allScreens: "전체 화면",
      sharedFiles: "공통으로 생성되는 파일",
      cliHandoff: "CLI 사용",
      downloadZip: "ZIP으로 받기",
      downloadCurrent: "현재 파일 받기",
      downloadBundle: "JSON 번들 받기",
      backToEditor: "편집기로 돌아가기",
      generatedFiles: "생성된 파일",
      copy: "복사",
      saveZip: "ZIP 저장",
      saveCurrentFile: "현재 파일 저장",
      exportUnavailable: "내보낼 프로젝트를 찾을 수 없습니다",
      exportUnavailableBody: "현재 로컬 저장소에 이 프로젝트 데이터가 없습니다."
    },
    help: {
      title: "작업 도움말 센터",
      description: "무엇을 먼저 눌러야 하는지, 어디서 색상을 바꾸는지, 언제 코드를 내보내는지 순서대로 안내합니다.",
      toc: "목차",
      sections: {
        start: "1. 시작 전에 알아두기",
        firstProject: "2. 첫 프로젝트 만드는 순서",
        colors: "3. 색상 바꾸기",
        settings: "4. 설정 바꾸기",
        export: "5. 코드 내보내기",
        troubleshooting: "6. 자주 막히는 문제"
      }
    }
  },
  en: {
    common: {
      appName: "Uiverse",
      projects: "Projects",
      settings: "Settings",
      help: "Help",
      helpCenter: "Help Center",
      feedback: "Feedback",
      createProject: "Create Project",
      export: "Export",
      openEditor: "Open Editor",
      returnToDashboard: "Return to dashboard",
      live: "live",
      language: "Language",
      korean: "Korean",
      english: "English",
      screen: "Screen",
      screens: "Screens",
      project: "Project",
      close: "Close",
      savedLocally: "Saved locally"
    },
    topHeader: {
      badge: "Intuitive visual builder",
      quickLink: "Workflow"
    },
    workspaceNav: {
      eyebrow: "Workspace",
      title: "Uiverse Studio",
      description: "Manage projects, settings, and help from one place.",
      elements: "Core features",
      elementLine1: "Add elements with a click",
      elementLine2: "Edit color and layout without code",
      elementLine3: "Export React or HTML code"
    },
    dashboard: {
      badge: "Local UI planning tool",
      title: "Build screen structure before you write app code.",
      description: "Create a project, choose a screen, add elements, adjust color, layout, and spacing, then export code.",
      searchPlaceholder: "Search projects or descriptions",
      quickStartTitle: "Start here if this is your first time",
      quickStartSteps: [
        "Create a new project.",
        "Choose a screen from the left panel.",
        "Add elements, then change text and color on the right."
      ],
      quickStartHelp: "Open detailed help",
      quickStartCreate: "Create a project now",
      dashboardTitle: "Project dashboard",
      dashboardDescription: "Each project can contain multiple screens and export code per screen.",
      recentTitle: "Recent activity",
      recentDescription: "Jump back into recently edited projects.",
      metrics: {
        projects: "Projects",
        screens: "Screens",
        components: "Components"
      },
      cardScreens: "screens",
      cardNodes: "nodes"
    },
    settings: {
      eyebrow: "Settings",
      title: "Change language, accent color, and default export format easily.",
      description: "We show the most important options first so the interface stays clear.",
      profileTitle: "Basic setup",
      profileDescription: "Stored locally in `uiverse.settings.v1`.",
      profileName: "Name",
      email: "Email",
      exportTarget: "Default export format",
      accentColor: "Accent color",
      accentHelp: "Pick from swatches or the palette. Manual color code entry is optional.",
      language: "Display language",
      storageTitle: "Storage",
      storageDescription: "This is what the app stores locally.",
      inspectJson: "Inspect JSON",
      storageProjects: "Stores project, screen, element tree, and last opened screen data.",
      storageSettings: "Stores language, accent color, and default export format.",
      summaryTitle: "System summary",
      themeMode: "Theme",
      darkOnly: "Dark-only V1",
      exportFormats: "Export formats",
      dataModel: "Structure",
      summaryModel: "User -> Project -> Screen -> Element"
    },
    editor: {
      project: "Project",
      screens: "Screens",
      elementPalette: "Add elements",
      clickToInsert: "Click to insert",
      nodeTree: "Layer tree",
      dragOnCanvas: "Move on canvas",
      dragInLayers: "Reorder in layers panel",
      visualEditor: "Visual editor",
      arrangement: "Layout arrangement",
      arrangementHint: "Apply vertical, horizontal, 2-column, or 3-column structures with one click.",
      exportView: "Code view",
      canvasTab: "Canvas",
      codeTab: "Code",
      livePreview: "Live React/Tailwind preview",
      livePreviewHint: "Generated from the current screen.",
      inspector: "Inspector",
      layerTab: "Layers",
      contentTab: "Content",
      styleTab: "Styles",
      layerSearchPlaceholder: "Search layers",
      layerHint: "Drag layers to reorder them, or drop them on a container to move them inside.",
      styleHint: "The quick cards stay on top, and the longer numeric controls stay folded underneath.",
      addInside: "Add inside",
      deleteLayer: "Delete layer",
      moveUp: "Move up",
      moveDown: "Move down",
      cannotDeleteRoot: "The root screen cannot be deleted.",
      addStack: "Add stack",
      content: "Content",
      layerName: "Layer name",
      textValue: "Text",
      buttonLabel: "Button label",
      placeholder: "Placeholder",
      imageSrc: "Image URL",
      altText: "Alt text",
      inherit: "Use inherited value",
      breakpointLabel: "Current breakpoint",
      previewWidth: "Preview width",
      noSelection: "Select one element from the canvas or layer tree.",
      noLayerSelection: "No layer selected.",
      projectNotFound: "Project not found",
      projectNotFoundBody: "The selected project or screen is not available in local storage.",
      deviceDesktop: "Desktop",
      deviceTablet: "Tablet",
      deviceMobile: "Mobile",
      groups: {
        typography: "Typography",
        layout: "Layout",
        background: "Background",
        border: "Border",
        effects: "Effects"
      },
      properties: {
        position: "Position",
        top: "Top",
        left: "Left",
        right: "Right",
        bottom: "Bottom",
        zIndex: "Layer order",
        fontSize: "Font size",
        fontWeight: "Font weight",
        lineHeight: "Line height",
        letterSpacing: "Letter spacing",
        textAlign: "Text align",
        color: "Text color",
        display: "Display",
        direction: "Direction",
        gap: "Gap",
        align: "Align items",
        justify: "Justify",
        gridColumns: "Columns",
        width: "Width",
        height: "Height",
        padding: "Padding",
        margin: "Margin",
        backgroundColor: "Background color",
        backgroundGradient: "Background gradient",
        borderStyle: "Border style",
        borderWidth: "Border width",
        borderColor: "Border color",
        borderRadius: "Border radius",
        borderTopLeftRadius: "Top left radius",
        borderTopRightRadius: "Top right radius",
        borderBottomRightRadius: "Bottom right radius",
        borderBottomLeftRadius: "Bottom left radius",
        opacity: "Opacity",
        boxShadow: "Box shadow"
      },
      options: {
        position: { static: "Flow", relative: "Reference box", absolute: "Free placement" },
        display: { block: "Block", flex: "Flex", grid: "Grid", none: "Hidden" },
        direction: { row: "Row", column: "Column" },
        align: { start: "Start", center: "Center", end: "End", stretch: "Stretch" },
        justify: { start: "Start", center: "Center", end: "End", between: "Space between", around: "Space around" },
        gridColumns: { "1": "1 column", "2": "2 columns", "3": "3 columns", "4": "4 columns" },
        borderStyle: { solid: "Solid", dashed: "Dashed", none: "None" },
        textAlign: { left: "Left", center: "Center", right: "Right" }
      },
      presets: {
        stack: "Vertical stack",
        row: "Horizontal row",
        twoColumn: "2-column layout",
        threeColumn: "3-column layout",
        cardGrid: "Card grid",
        compactGap: "Compact",
        normalGap: "Normal",
        roomyGap: "Roomy",
        tightPadding: "Tight padding",
        normalPadding: "Normal padding",
        widePadding: "Wide padding"
      }
    },
    exportView: {
      title: "Code export",
      description: "Review shared globals and per-screen files together, then download only what you need.",
      target: "Export target",
      screenFilter: "Screen filter",
      allScreens: "All screens",
      sharedFiles: "Shared scaffold files",
      cliHandoff: "CLI handoff",
      downloadZip: "Download ZIP",
      downloadCurrent: "Download current file",
      downloadBundle: "Download JSON bundle",
      backToEditor: "Back to editor",
      generatedFiles: "Generated files",
      copy: "Copy",
      saveZip: "Save ZIP",
      saveCurrentFile: "Save current file",
      exportUnavailable: "Export source unavailable",
      exportUnavailableBody: "This project does not exist in local storage."
    },
    help: {
      title: "Help center",
      description: "Learn what to click first, where to change colors, and when to export code.",
      toc: "Table of contents",
      sections: {
        start: "1. Before you begin",
        firstProject: "2. Your first project",
        colors: "3. Changing colors",
        settings: "4. Changing settings",
        export: "5. Exporting code",
        troubleshooting: "6. Common issues"
      }
    }
  }
} as const;

export type AppCopy = (typeof copy)[Language];

export function useLanguage(): Language {
  return useUiverseStore((state) => state.settings.language);
}

export function useCopy(): AppCopy {
  const language = useLanguage();
  return copy[language];
}

export function formatLocalDate(value: string, language: Language): string {
  return new Date(value).toLocaleDateString(language === "ko" ? "ko-KR" : "en-US");
}
